### ISSUE TITLE
Explore implementing a universal parameter changepoint function for model

### ISSUE THREAD

**Issue by smjenness** [EpiModel/SexualDistancing#1]
This would use @AdrienLeGuillou's approach from his SFO model to modify an arbitrarily defined set of parameters. 

We will just need to check that this works both for clinical (HIV screening, ART care, STI treatment...) parameters as well as behavioral parameters, which includes network parameters stored in a separate list. Here is an example of how they are pulled and modified in the current version of EpiModelHIV-p:
https://github.com/EpiModel/EpiModelHIV-p/blob/SexualDistancing_sj1/R/mod.simnet.R#L21-L33

@laurammann, @AdrienLeGuillou: please meet this week to discuss implementing this and testing this approach in the model.

**Comment by AdrienLeGuillou** [comment]
I just pushed on my branch [a commit adding this functionality.](https://github.com/EpiModel/EpiModelHIV-p/commit/93d1d14007fc258ac893c6c83466108edb1795c9) 

``` r
param$param_updaters <-  list(
    list(
      at = 4860,
        param = list(
          hiv.test.rate = rep(0.0128, 3),
          trans.scale = c(1.61, 0.836, 0.622)
       )
    ),
    list(
     at = 5160,
     verbose = FALSE,
       param = list(
         hiv.test.rate = function(x) x * 3,
          trans.scale = function(x) x^2 / 3
       )
     )
   )
 )
```
In this example, their is two updaters, one at timestep 4860 that will replace the values of `hiv.test.rate` and `trans.scale`. The second one occurs at timestep 5160, and modifies the same parameters, but this time by applying the given function to the current value `x * 3` and `x^2 / 3` respectively.

The `update_list` function at the top of "mod.dat_updater.R" is able to handle nested lists. Thus, for `nwparam`, I could make a similar function that would look like this in terms of input:

``` r
param$nwparam_updaters <- list(
  list(
    at = 4680,
    network = 1,
    nwparam = list(
      coef.diss = list(
        coef.adj = function (x) {
           x[1] <- x[1] + log(relevent_rr)
           return(x)
        }
      )
    )
  )
)
```

However, I find this approach quite inelegant and needing to update the network parameters without a `set_nwparam` function (analogous to `get_nwparam`) feels hacky. I would suggest for this situation highlighted by @smjenness to have two Odds Ratios per network: `netresim.main.form.rr` and `netresim.main.disl.rr` (for the main network), apply them at ALL time step, but vary their values using the mechanism presented above. They would be 1 at first so nothing happens and will have new values at some given time steps.

**Comment by AdrienLeGuillou** [comment]
@laurammann: I implemented what we discussed [my branch](https://github.com/EpiModel/EpiModelHIV-p/blob/SexualDistancing/R/mod.simnet.R#L23-L26) (for all three networks) and an example use [is available here](https://github.com/EpiModel/SexualDistancing/blob/adrien_tests/R/16-test_sex_dist_sim.R)
